---
  - hosts: webservers

    tasks:
    - name: add nginx repo
      copy: src=files/nginx.repo dest=/etc/yum.repos.d/nginx.repo
    - name: install nginx
      yum: name=nginx state=latest
      notify:
      - restart nginx

    handlers:    
    - name: restart nginx
      action: service name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes

  - hosts: databases

    tasks:
    - name: add mongodb repo
      copy: src=files/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo
    - name: install mongodb-org
      yum: name=mongodb-org state=latest
      notify:
      - restart mongodb

    handlers:    
    - name: restart mongodb
      action: service name=mongod pattern=/etc/init.d/mongod state=restarted enabled=yes

