---
  - hosts: webservers

    tasks:
    - name: add nginx repo
      copy: src=files/nginx.repo dest=/etc/yum.repos.d/nginx.repo
    - name: install nginx
      yum: name=nginx state=latest
      notify:
      - restart nginx

    handlers:    
    - name: restart nginx
      action: service name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes
